# Generated by Django 5.2.8 on 2025-11-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='category',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='description',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='image',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('college', 'College'), ('institute', 'Institute')], default='institutions', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='education_system',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='fees_structure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='infrastructure_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='management_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='placement_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='practical_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='staff_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
