# Generated by Django 5.2.8 on 2025-11-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_institution_location_remove_institution_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegereview',
            name='institution',
        ),
        migrations.AlterModelOptions(
            name='collegereview',
            options={'ordering': ['-created_at'], 'verbose_name': 'College Review', 'verbose_name_plural': 'College Reviews'},
        ),
        migrations.RenameField(
            model_name='collegereview',
            old_name='infrastructure',
            new_name='infrastructure_review',
        ),
        migrations.RenameField(
            model_name='collegereview',
            old_name='mobile',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='collegereview',
            old_name='security',
            new_name='security_review',
        ),
        migrations.AddField(
            model_name='collegereview',
            name='college_name',
            field=models.CharField(default='Sample College', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collegereview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='collegereview',
            name='user_name',
            field=models.CharField(default='Anonymous User', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='collegereview',
            table='college_reviews',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
