# Generated by Django 6.0.1 on 2026-02-14 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userprofile_bio'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE app_userprofile MODIFY COLUMN bio LONGTEXT NULL;",
            reverse_sql="ALTER TABLE app_userprofile MODIFY COLUMN bio LONGTEXT NOT NULL;" 
        ),
        migrations.RunSQL(
            "ALTER TABLE app_userprofile MODIFY COLUMN location VARCHAR(100) NULL;",
            reverse_sql="ALTER TABLE app_userprofile MODIFY COLUMN location VARCHAR(100) NOT NULL;" 
        ),
        migrations.RunSQL(
            "ALTER TABLE app_userprofile MODIFY COLUMN birth_date DATE NULL;",
            reverse_sql="ALTER TABLE app_userprofile MODIFY COLUMN birth_date DATE NOT NULL;" 
        ),
    ]
