# Generated by Django 5.2.8 on 2025-11-15 08:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_institution_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='location',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='type',
        ),
        migrations.AddField(
            model_name='institution',
            name='city',
            field=models.CharField(default='Chennai', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='CollegeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('education_system', models.TextField(blank=True, null=True)),
                ('staff_review', models.TextField(blank=True, null=True)),
                ('practical_experience', models.TextField(blank=True, null=True)),
                ('fees_structure', models.TextField(blank=True, null=True)),
                ('management_review', models.TextField(blank=True, null=True)),
                ('sports_cultural', models.TextField(blank=True, null=True)),
                ('placement_review', models.TextField(blank=True, null=True)),
                ('placement_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('travel_expense', models.TextField(blank=True, null=True)),
                ('entrepreneurship_support', models.TextField(blank=True, null=True)),
                ('canteen_available', models.BooleanField(default=False)),
                ('canteen_review', models.TextField(blank=True, null=True)),
                ('hostel_available', models.BooleanField(default=False)),
                ('hostel_review', models.TextField(blank=True, null=True)),
                ('infrastructure', models.TextField(blank=True, null=True)),
                ('security', models.TextField(blank=True, null=True)),
                ('overall_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('overall_review', models.TextField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
