# Generated by Django 6.0.1 on 2026-02-15 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_userprofile_is_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collegereview',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collegereview',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='saved_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
