# Generated by Django 6.0.1 on 2026-06-02 10:10

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profile_images/', validators=[app.models.validate_image_size]),
        ),
    ]
