# Generated by Django 5.2.8 on 2025-11-15 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('education_system', models.TextField(blank=True, null=True)),
                ('staff_review', models.TextField(blank=True, null=True)),
                ('practical_experience', models.TextField(blank=True, null=True)),
                ('fees_structure', models.TextField(blank=True, null=True)),
                ('management_review', models.TextField(blank=True, null=True)),
                ('sports_cultural', models.TextField(blank=True, null=True)),
                ('placement_review', models.TextField(blank=True, null=True)),
                ('placement_rating', models.IntegerField(blank=True, null=True)),
                ('travel_expense', models.TextField(blank=True, null=True)),
                ('entrepreneurship_support', models.TextField(blank=True, null=True)),
                ('canteen_available', models.BooleanField(default=False)),
                ('canteen_review', models.TextField(blank=True, null=True)),
                ('hostel_available', models.BooleanField(default=False)),
                ('hostel_review', models.TextField(blank=True, null=True)),
                ('infrastructure_review', models.TextField(blank=True, null=True)),
                ('security_review', models.TextField(blank=True, null=True)),
                ('overall_rating', models.IntegerField()),
                ('overall_review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_colleges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews_college_reviews',
            },
        ),
    ]
