# Generated by Django 5.2.8 on 2025-11-15 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegereview',
            name='user',
        ),
        migrations.AlterModelTable(
            name='collegereview',
            table=None,
        ),
    ]
