# Generated by Django 5.2.8 on 2025-11-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_collegereview_user_alter_collegereview_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegereview',
            name='canteen_review',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='collegereview',
            name='education_system',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='collegereview',
            name='entrepreneurship_support',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='collegereview',
            name='fees_structure',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='collegereview',
            name='hostel_review',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='collegereview',
            name='infrastructure_review',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='collegereview',
            name='management_review',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='collegereview',
            name='overall_review',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='collegereview',
            name='placement_review',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='collegereview',
            name='practical_experience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='collegereview',
            name='security_review',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='collegereview',
            name='sports_cultural',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='collegereview',
            name='staff_review',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='collegereview',
            name='travel_expense',
            field=models.TextField(blank=True, default=''),
        ),
    ]
